export const SET_ALL_ARTICLES = 'SET_ALL_ARTICLES';

export const SET_FILTER_ARTICLES = 'SET_FILTER_ARTICLES';

export const SET_DISPLAY_ARTICLES = 'SET_DISPLAY_ARTICLES';

export const SET_PROCESSING_ID = 'SET_PROCESSING_ID';
